In [ ]:
# Hypothesis Testing
# 3. Chi Square Test

In [ ]:
# Example 1

In [1]:
import numpy as np
from scipy.stats import chi2

In [4]:
ob = np.array([22, 17, 20, 26, 22, 13])
ex = np.array([20, 20, 20, 20, 20, 20])

In [8]:
chi_cal = np.sum(np.square(ob - ex)/ex)
chi_cal

np.float64(5.1000000000000005)

In [23]:
# significance level (alpha)
alpha = 0.05  

# degrees of freedom
df = 5  

# chi-squared critical value
chi_table = chi2.ppf(1 - alpha, df)

In [24]:
chi_table

np.float64(11.070497693516351)

In [ ]:
# die is fair

In [ ]:
# Example 2

In [2]:
row1 = np.array([40, 45, 25, 10])
row2 = np.array([35, 30, 20, 30])

In [3]:
row1, row2

(array([40, 45, 25, 10]),
 array([35, 30, 20, 30]),
 array([40, 35]),
 array([45, 30]),
 array([25, 20]),
 array([10, 30]))

In [15]:
s_no = np.sum(row1) + np.sum(row2)
s_no

np.int64(235)

In [5]:
sum_r1 = np.sum(row1)
sum_r2 = np.sum(row2)


In [9]:
s_no, sum_r1, sum_r2

(np.int64(235),
 np.int64(120),
 np.int64(115),
 np.int64(75),
 np.int64(75),
 np.int64(45),
 np.int64(40))

In [26]:
sum_row = np.array([sum_r1, sum_r2])
sum_col = row1 + row2
sum_row, sum_col

(array([120, 115]), array([75, 75, 45, 40]))

In [27]:
for i in sum_row : 
    for j in sum_col : 
        print(i, j)

120 75
120 75
120 45
120 40
115 75
115 75
115 45
115 40


In [28]:
exp = []
for i in sum_row : 
    for j in sum_col : 
        value = (i * j)/s_no
        exp.append(value)

In [29]:
exp

[np.float64(38.297872340425535),
 np.float64(38.297872340425535),
 np.float64(22.97872340425532),
 np.float64(20.425531914893618),
 np.float64(36.702127659574465),
 np.float64(36.702127659574465),
 np.float64(22.02127659574468),
 np.float64(19.574468085106382)]

In [20]:
obj = np.array([40, 45, 25, 10, 35, 30, 20, 30])
obj

array([40, 45, 25, 10, 35, 30, 20, 30])

In [25]:
len(obj), len(exp)

(8, 8)

In [30]:
chi_cal = np.sum(np.square(obj - exp)/exp)
chi_cal

np.float64(13.788747987117553)

In [32]:
# significance level (alpha)
alpha = 0.05  

# degrees of freedom
# df = (row - 1) * (col - 1)
df = (2 - 1) * (4 - 1)

# chi-squared critical value
chi_table = chi2.ppf(1 - alpha, df)

In [33]:
alpha, df, chi_table

(0.05, 3, np.float64(7.814727903251179))

In [ ]:
# Ha is association