In [ ]:
#  Hypothesis Testing
# 1. Z-Test

In [ ]:
# Example 1

In [1]:
import numpy as np
import scipy.stats as st

In [2]:
s_x = 90
p_u = 82
p_std = 20
n = 81
ap = 0.05

In [3]:
z_cal = (s_x - p_u) / (p_std / np.sqrt(n))
z_cal

np.float64(3.5999999999999996)

In [4]:
z_table = st.norm.ppf(1 - ap)
z_table

np.float64(1.6448536269514722)

In [5]:
if z_table < z_cal :
    print("ha is right")
else : 
    print("ho is right")

ha is right


In [ ]:
# Example 2

In [6]:
Old_design_data = np.array([45.2, 42.8, 38.9, 43.5, 41.0, 44.6, 40.5, 42.7, 39.8, 41.4, 44.3, 39.7, 42.1, 40.6, 43.0, 42.2, 41.5, 39.6, 44.0, 43.1, 38.7, 43.9, 42.0, 41.9, 42.8, 43.7, 41.3, 40.9, 42.5, 41.63])
New_design_data = np.array([48.5, 49.1, 58.2, 47.8, 48.7, 49.9, 48.0, 50.5, 49.8, 49.6, 48.2, 48.9, 49.7, 50.3, 49.4, 50.1, 48.6, 48.3, 49.0, 50.0, 48.4, 49.3, 49.5, 48.8, 50.6, 50.4, 48.1, 49.2, 50.7, 50.8])
Old_design_data, New_design_data

(array([45.2 , 42.8 , 38.9 , 43.5 , 41.  , 44.6 , 40.5 , 42.7 , 39.8 ,
        41.4 , 44.3 , 39.7 , 42.1 , 40.6 , 43.  , 42.2 , 41.5 , 39.6 ,
        44.  , 43.1 , 38.7 , 43.9 , 42.  , 41.9 , 42.8 , 43.7 , 41.3 ,
        40.9 , 42.5 , 41.63]),
 array([48.5, 49.1, 58.2, 47.8, 48.7, 49.9, 48. , 50.5, 49.8, 49.6, 48.2,
        48.9, 49.7, 50.3, 49.4, 50.1, 48.6, 48.3, 49. , 50. , 48.4, 49.3,
        49.5, 48.8, 50.6, 50.4, 48.1, 49.2, 50.7, 50.8]))

In [7]:
mean_new = np.mean(New_design_data)
mean_old = np.mean(Old_design_data)
mean_new, mean_old

(np.float64(49.61333333333333), np.float64(41.99433333333334))

In [11]:
pop_std = 2.5
n_sp = len(New_design_data)
apl = 0.05

In [9]:
z_cal = (mean_new - mean_old) / (pop_std / np.sqrt(n_sp))
z_cal

np.float64(16.692392662527425)

In [12]:
z_table = st.norm.ppf(1 - apl)
z_table

np.float64(1.6448536269514722)

In [13]:
z_cal, z_table

(np.float64(16.692392662527425), np.float64(1.6448536269514722))

In [14]:
if z_cal > z_table :
    print("ha is right")
else :
    print("ho is right")

ha is right


In [ ]:
# 2. T-Test
# Example 1 

In [8]:
t_table = st.t.ppf(0.05, 24)
t_table

np.float64(-1.7108820799094282)

In [9]:
s_x = 148
p_u = 150
s_std = 5
sam_no = 25

In [10]:
t_cal = (s_x - p_u) / (s_std / np.sqrt(25))
t_cal

np.float64(-2.0)

In [11]:
if t_cal < t_table :
    print("ha is right")
else :
    print("ho is right")

ha is right


In [ ]:
# Example 2

In [14]:
t_table = st.t.ppf(1-0.025, 38)
t_table

np.float64(2.024394163911969)

In [18]:
t_cal = (80 - 75) / np.sqrt((25/20) + (26/20))
t_cal

np.float64(3.1311214554257476)

In [21]:
if t_cal > t_table :
    print("ha is right")
else :
    print("ho is right")

ha is right


In [ ]:
# Example 3

In [23]:
# Before: 50, 60, 45, 65, 55, 70, 40, 75, 80, 65, 70, 60, 50, 55, 45, 75, 60, 50, 65, 70
# After: 60, 70, 55, 75, 65, 80, 50, 85, 90, 70, 75, 65, 55, 60, 50, 80, 65, 55, 70, 75 

In [25]:
t_table = st.t.ppf(1 - 0.025, 19)
t_table

np.float64(2.093024054408263)

In [29]:
Before = np.array([50, 60, 45, 65, 55, 70, 40, 75, 80, 65, 70, 60, 50, 55, 45, 75, 60, 50, 65, 70])
After = np.array([60, 70, 55, 75, 65, 80, 50, 85, 90, 70, 75, 65, 55, 60, 50, 80, 65, 55, 70, 75])
Before, After

(array([50, 60, 45, 65, 55, 70, 40, 75, 80, 65, 70, 60, 50, 55, 45, 75, 60,
        50, 65, 70]),
 array([60, 70, 55, 75, 65, 80, 50, 85, 90, 70, 75, 65, 55, 60, 50, 80, 65,
        55, 70, 75]))

In [30]:
mean_a = np.mean(After)
mean_b = np.mean(Before)
std_a = np.std(After)
std_b = np.std(Before)
no_a = len(After)
no_b = len(Before)

mean_a, mean_b, std_a, std_b, no_a, no_b

(np.float64(67.5),
 np.float64(60.25),
 np.float64(11.236102527122116),
 np.float64(11.008519428151999),
 20,
 20)

In [34]:
t_cal = (mean_a - mean_b) / (np.sqrt(((std_a * std_a)/no_a) + ((std_b * std_b)/no_b)))
t_cal

np.float64(2.061200527128206)

In [35]:
if t_cal > t_table :
    print("ha is right")
else :
    print("ho is right")

ho is right
